apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "golang-ci-cd"
  annotations:
     github.com/project-slug: shivanshhhhh/golang-test3
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
