name: Release to Docker Hub

on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 
          password: 

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: /:latest

      - name: Image digest
        run: echo 
